Resources:
  myDynamoDBTable: #Logical Id of the resource
    Type: AWS::DynamoDB::Table

    Properties:
      TableName: "Personas"
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "N"

      KeySchema:
        - AttributeName: "id" # Partition Key
          KeyType: "HASH"

      ProvisionedThroughput:
        ReadCapacityUnits: 10
        WriteCapacityUnits: 10
